library("data.table")
ngrams<-fread("ngrams.r.txt")
tail(ngrams)
names(ngrams)
summary(ngrams)
library(psych)
describe(ngrams)
combn(ngrams, 3)
ngrams$word1
table(ngrams$occurrences)
table(ngrams$word1)
plot(ngrams$occurrences, ngrams$occurrences)
barplot(ngrams$occurrences, main="Barplot of Occurrences")
hist(ngrams$occurrences)
boxplot(ngrams$occurrences)
jpeg("ngramsPlot.jpg", width=200, height=200)
barplot(ngrams$occurrences)
dev.off()
